// i18n minimal untuk PO Tracker (ID/EN toggle).
import { createContext, useContext, useState, useCallback, useMemo } from "react";
import { STAGE_NAMES } from "@/lib/poStages";

const STAGE_NAMES_EN = {
  1: "Waiting Paper / Single Face PO",
  2: "Waiting CTCP Order",
  3: "Waiting Die Cut Order",
  4: "Paper Cutting",
  5: "Printing",
  6: "Finishing",
  7: "Die Cutting",
  8: "Kopek Process",
  9: "Gluing",
  10: "Packing",
  11: "Done & Delivery",
};

const DICT = {
  id: {
    overview: "Ringkasan",
    tapToFilter: "Klik kartu untuk memfilter daftar PO.",
    totalPO: "Total PO",
    activePO: "PO Aktif",
    completedPO: "PO Selesai",
    poList: "Daftar PO",
    newPO: "PO Baru",
    search: "Cari nomor PO, klien, atau item...",
    filterAll: "Semua Status",
    allMonths: "Semua Bulan",
    exportPdf: "Export PDF",
    noData: "Belum ada PO.",
    stage: "Tahap",
    detail: "Detail",
    edit: "Edit",
    confirmDelete: "Yakin hapus PO ini?",
    poNumber: "Nomor PO",
    cancel: "Batal",
    delete: "Hapus",
    clientName: "Nama Klien",
    itemType: "Jenis Item",
    material: "Bahan",
    paperSize: "Ukuran Kertas",
    quantity: "Quantity",
    poDate: "Tanggal PO",
    printMachine: "Mesin Cetak",
    estStart: "Est. Mulai Produksi",
    estEnd: "Est. Selesai Produksi",
    stagesUsed: "Tahapan Dipakai",
    conflictTitle: "Peringatan Bentrok Jadwal",
    conflictDesc: "Rentang produksi PO ini bentrok dengan PO lain di bawah:",
    noConflict: "Tidak ada bentrok jadwal.",
    notes: "Catatan",
    save: "Simpan",
    saving: "Menyimpan...",
    progress: "Progress Produksi",
    done: "Selesai",
    pending: "Belum",
    reopen: "Buka Kembali",
    markDone: "Tandai Selesai",
    needSingleFace: "Butuh Single Face",
    paperArrived: "Kertas Sudah Datang",
    sfArrived: "Single Face Sudah Datang",
    arrived: "Sudah Datang",
    arrivalDate: "Tanggal Kedatangan",
    finishingType: "Jenis Finishing",
    glueType: "Jenis Lem",
    custom: "Custom / Lainnya",
    customPlaceholder: "Tulis manual jika tidak ada di daftar...",
    machine: "Mesin",
    delivery: "Pengiriman",
    printCompleted: "Cetak Sudah Selesai",
    waitingShip: "Menunggu Kirim",
    shipDate: "Tanggal Kirim",
    driverName: "Nama Supir",
    scheduleDelivery: "Jadwalkan Kirim",
    reschedule: "Jadwal Ulang",
    shipSuccess: "Berhasil Terkirim",
    shipFailed: "Gagal Kirim",
    failReason: "Alasan Gagal",
    photoOptional: "Foto opsional",
    deliveryHistory: "Riwayat Pengiriman",
    attempt: "Percobaan",
    uploadPhoto: "Foto Bukti",
    history: "Riwayat Perubahan",
    createdBy: "Dibuat oleh",
    keterangan: "Keterangan",
    keteranganPlaceholder: "Catatan tambahan untuk tahap ini...",
    schedule: "Kalender Jadwal",
    legend: "Legenda",
    productionBlock: "Blok Produksi",
    scheduleStage: "Jadwalkan Tahap",
    selectPO: "Pilih PO",
    selectStage: "Pilih Tahap",
    scheduledOn: "Terjadwal",
    noScheduleThisDay: "Belum ada jadwal untuk hari ini.",
    addSchedule: "Tambah",
    b_waiting1: "Menunggu 1", b_waiting2: "Menunggu 2", b_waiting3: "Menunggu 3",
    b_stage4: "Potong", b_stage5: "Cetak", b_stage6: "Finishing", b_stage7: "Plong", b_stage8: "Kopek", b_stage9: "Lem", b_stage10: "Packing",
    b_printing: "Finalisasi", b_printdone: "Belum Kirim", b_failed: "Gagal Kirim", b_completed: "Selesai", b_nostages: "Tanpa Tahap",
  },
  en: {
    overview: "Overview",
    tapToFilter: "Tap a card to filter PO list.",
    totalPO: "Total PO",
    activePO: "Active PO",
    completedPO: "Completed PO",
    poList: "PO List",
    newPO: "New PO",
    search: "Search PO number, client, or item...",
    filterAll: "All Status",
    allMonths: "All Months",
    exportPdf: "Export PDF",
    noData: "No PO yet.",
    stage: "Stage",
    detail: "Detail",
    edit: "Edit",
    confirmDelete: "Delete this PO?",
    poNumber: "PO Number",
    cancel: "Cancel",
    delete: "Delete",
    clientName: "Client Name",
    itemType: "Item Type",
    material: "Material",
    paperSize: "Paper Size",
    quantity: "Quantity",
    poDate: "PO Date",
    printMachine: "Printing Machine",
    estStart: "Est. Production Start",
    estEnd: "Est. Production End",
    stagesUsed: "Enabled Stages",
    conflictTitle: "Schedule Conflict",
    conflictDesc: "This PO production overlaps with:",
    noConflict: "No schedule conflict.",
    notes: "Notes",
    save: "Save",
    saving: "Saving...",
    progress: "Production Progress",
    done: "Done",
    pending: "Pending",
    reopen: "Reopen",
    markDone: "Mark Done",
    needSingleFace: "Needs Single Face",
    paperArrived: "Paper Arrived",
    sfArrived: "Single Face Arrived",
    arrived: "Arrived",
    arrivalDate: "Arrival Date",
    finishingType: "Finishing Type",
    glueType: "Glue Type",
    custom: "Custom / Other",
    customPlaceholder: "Write manually if not listed...",
    machine: "Machine",
    delivery: "Delivery",
    printCompleted: "Print Completed",
    waitingShip: "Waiting Shipment",
    shipDate: "Ship Date",
    driverName: "Driver Name",
    scheduleDelivery: "Schedule Delivery",
    reschedule: "Reschedule",
    shipSuccess: "Shipped Successfully",
    shipFailed: "Delivery Failed",
    failReason: "Failure Reason",
    photoOptional: "Photo optional",
    deliveryHistory: "Delivery History",
    attempt: "Attempt",
    uploadPhoto: "Proof Photo",
    history: "Change History",
    createdBy: "Created by",
    keterangan: "Notes",
    keteranganPlaceholder: "Additional notes for this stage...",
    schedule: "Schedule Calendar",
    legend: "Legend",
    productionBlock: "Production Block",
    scheduleStage: "Schedule Stage",
    selectPO: "Select PO",
    selectStage: "Select Stage",
    scheduledOn: "Scheduled",
    noScheduleThisDay: "No schedule for this day.",
    addSchedule: "Add",
    b_waiting1: "Waiting 1", b_waiting2: "Waiting 2", b_waiting3: "Waiting 3",
    b_stage4: "Cutting", b_stage5: "Printing", b_stage6: "Finishing", b_stage7: "Die Cut", b_stage8: "Kopek", b_stage9: "Gluing", b_stage10: "Packing",
    b_printing: "Finalizing", b_printdone: "Not Shipped", b_failed: "Failed", b_completed: "Completed", b_nostages: "No Stages",
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => {
    if (typeof window === "undefined") return "id";
    return localStorage.getItem("sca_lang") || "id";
  });

  const setLangPersist = useCallback((v) => {
    setLang(v);
    if (typeof window !== "undefined") localStorage.setItem("sca_lang", v);
  }, []);

  const t = useCallback((key) => DICT[lang]?.[key] || DICT.id[key] || key, [lang]);
  const stageName = useCallback((n) => (lang === "en" ? STAGE_NAMES_EN[n] : STAGE_NAMES[n]) || `Stage ${n}`, [lang]);

  const value = useMemo(() => ({ lang, setLang: setLangPersist, t, stageName }), [lang, setLangPersist, t, stageName]);
  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext) || { lang: "id", setLang: () => {}, t: (k) => k, stageName: (n) => STAGE_NAMES[n] };
